[package]
name = "cr7"
version = "0.1.0"
authors = ["Bernardo Lins <bernardolins28@gmail.com>"]

[dependencies]
clap = {version = "2.32", features = ["yaml"]}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
